CREATE TABLE [dbo].[Positions] (
    [Id]                  BIGINT         IDENTITY (1, 1) NOT NULL,
    [Name]                NVARCHAR (500) NULL,
    [FlightId]            NVARCHAR (500) NULL,
    [FlightIdentity]      NVARCHAR (500) NULL,
    [Temp1Latitude]       DECIMAL (9, 6) NOT NULL,
    [Temp1Longitude]      DECIMAL (9, 6) NOT NULL,
    [Temp1Altitude]       INT            NOT NULL,
    [Temp1Speed]          INT            NOT NULL,
    [Temp1Heading]        INT            NOT NULL,
    [Temp1TimeStamp]      DATETIME       NOT NULL,
    [Temp1EpochTimeStamp] BIGINT         NULL,
    [Temp2Latitude]       DECIMAL (9, 6) NULL,
    [Temp2Longitude]      DECIMAL (9, 6) NULL,
    [Temp2Altitude]       INT            NULL,
    [Temp2Speed]          INT            NULL,
    [Temp2Heading]        INT            NULL,
    [Temp2TimeStamp]      DATETIME       NULL,
    [Temp2EpochTimeStamp] BIGINT         NULL,
    [X1]                  DECIMAL (9, 6) NULL,
    [Y1]                  DECIMAL (9, 6) NULL,
    [Z1]                  INT            NULL,
    [X2]                  DECIMAL (9, 6) NULL,
    [Y2]                  DECIMAL (9, 6) NULL,
    [Z2]                  INT            NULL,
    [X3]                  DECIMAL (9, 6) NULL,
    [Y3]                  DECIMAL (9, 6) NULL,
    [Z3]                  INT            NULL,
    [X4]                  DECIMAL (9, 6) NULL,
    [Y4]                  DECIMAL (9, 6) NULL,
    [Z4]                  INT            NULL,
    [X5]                  DECIMAL (9, 6) NULL,
    [Y5]                  DECIMAL (9, 6) NULL,
    [Z5]                  INT            NULL,
    [X6]                  DECIMAL (9, 6) NULL,
    [Y6]                  DECIMAL (9, 6) NULL,
    [Z6]                  INT            NULL,
    [X7]                  DECIMAL (9, 6) NULL,
    [Y7]                  DECIMAL (9, 6) NULL,
    [Z7]                  INT            NULL,
    [X8]                  DECIMAL (9, 6) NULL,
    [Y8]                  DECIMAL (9, 6) NULL,
    [Z8]                  INT            NULL,
    [CreatedAtTimeStamp]  DATETIME       NULL,
    [IsInFlight]          BIT            CONSTRAINT [DF_Positions_IsInFlight] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Positions] PRIMARY KEY CLUSTERED ([Id] ASC)
);



