CREATE TABLE [dbo].[Position] (
    [Id]                     INT             IDENTITY (1, 1) NOT NULL,
    [Name]                   NVARCHAR (500)  NULL,
    [AircraftId]             INT             NOT NULL,
    [FlightId]               NVARCHAR (500)  NULL,
    [FlightIdentity]         NVARCHAR (500)  NULL,
    [Latitude1]              DECIMAL (9, 6)  NULL,
    [Longitude1]             DECIMAL (9, 6)  NULL,
    [Altitude1]              DECIMAL (18, 8) NULL,
    [Speed1]                 DECIMAL (18, 8) NULL,
    [Heading1]               DECIMAL (18, 8) NULL,
    [UtcTimeStamp1]          DATETIME        NULL,
    [Latitude2]              DECIMAL (9, 6)  NULL,
    [Longitude2]             DECIMAL (9, 6)  NULL,
    [Altitude2]              DECIMAL (18, 8) NULL,
    [Speed2]                 DECIMAL (18, 8) NULL,
    [Heading2]               DECIMAL (18, 8) NULL,
    [UtcTimeStamp2]          DATETIME        NULL,
    [Latitude3]              DECIMAL (9, 6)  NULL,
    [Longitude3]             DECIMAL (9, 6)  NULL,
    [Altitude3]              DECIMAL (18, 8) NULL,
    [Speed3]                 DECIMAL (18, 8) NULL,
    [Heading3]               DECIMAL (18, 8) NULL,
    [UtcTimeStamp3]          DATETIME        NULL,
    [X1]                     DECIMAL (18, 8) NULL,
    [Y1]                     DECIMAL (18, 8) NULL,
    [Z1]                     DECIMAL (18, 8) NULL,
    [X2]                     DECIMAL (18, 8) NULL,
    [Y2]                     DECIMAL (18, 8) NULL,
    [Z2]                     DECIMAL (18, 8) NULL,
    [X3]                     DECIMAL (18, 8) NULL,
    [Y3]                     DECIMAL (18, 8) NULL,
    [Z3]                     DECIMAL (18, 8) NULL,
    [Radius]                 DECIMAL (18, 8) NULL,
    [CreatedAtUtcTimeStamp]  DATETIME        NOT NULL,
    [ModifiedAtUtcTimeStamp] DATETIME        NULL,
    [IsInFlight]             BIT             NULL,
    [IsActive]               BIT             NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Position_Aircraft] FOREIGN KEY ([AircraftId]) REFERENCES [dbo].[Aircraft] ([Id])
);

