//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collision.Sql.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conflict
    {
        public int Id { get; set; }
        public int PositionId1 { get; set; }
        public int PositionId2 { get; set; }
        public Nullable<System.DateTime> ModifiedAtUtcTimeStamp { get; set; }
        public System.DateTime CreatedAtUtcTimeStamp { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Position Position1 { get; set; }
    }
}
